# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ethnt.me
title: Ethan Turkeltaub
subtitle: The weblog of Ethan Turkeltaub, student and web developer.
author: Ethan Turkeltaub
simple_search: http://google.com/search
description: The weblog of Ethan Turkeltaub.

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: http://feeds.feedburner.com/turkeltaub
subscribe_email: ethan.turkeltaub@gmail.com
# RSS feeds can list your email address if you like
email: ethan.turkeltaub@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:year/:month/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 7          # Posts per page on the blog index
pagination_dir: /      # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase
